server:
  port: 8888

spring:
  application:
    name: 'cactus'
  jackson:
    timeZone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss:SSS
    default-property-inclusion: non_null
    parser:
      allow-single-quotes: true
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    name: hikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/csg_cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 1000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-statement-timeout: 3 # 查询超时间,单位秒,不设置则无线等待
    default-fetch-size: 100
    map-underscore-to-camel-case: true
  type-aliases-package: com.mayikt.model