spring:
  application:
    name: cloud-user
  jackson:
    timeZone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss:SSS
    default-property-inclusion: non_null
    parser:
      allow-single-quotes: true
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    name: hikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/csg_cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 1000
    database: 1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-statement-timeout: 3 # 查询超时间,单位秒,不设置则无线等待
    default-fetch-size: 100
    map-underscore-to-camel-case: true
  type-aliases-package: com.mayikt.user.model

redis:
  database: csg_cloud
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
    roleList: 'ums:roleList'
    standerList: 'ums:standerList'
    sysOrg: 'ums:sysOrg'
  expire:
    common: 86400

jwt:
  tokenHeader: Authorization
  secret: csgcloud123456
  expiration: 604800
  tokenHead: Bearer

# 请求白名单
secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /system/user/login
      - /system/user/logout
      - /system/user/getToken

init:
  password: abcd1234
name: xiaoming4